#!/usr/bin/env python3
"""Independent arithmetic/source guard for balmer-rydberg-poams.html."""

from __future__ import annotations

import math
from pathlib import Path

C = 299_792_458.0
H = 6.626_070_15e-34
HBAR = H / (2 * math.pi)
M_E = 9.109_383_7139e-31
M_P = 1.672_621_925_95e-27
G = 6.674_30e-11
R_H = 10_967_758.340
NU_R = C * R_H
E_R = H * NU_R


def rate(lower: int, upper: int) -> float:
    assert upper > lower >= 1
    return NU_R * (1 / lower**2 - 1 / upper**2)


def wavelength_nm(lower: int, upper: int) -> float:
    return C / rate(lower, upper) * 1e9


# The line formula must equal subtraction of two ground-referenced terms.
for lower in (1, 2, 3):
    for upper in range(lower + 1, 9):
        term_upper = NU_R * (1 - 1 / upper**2)
        term_lower = NU_R * (1 - 1 / lower**2)
        assert math.isclose(
            term_upper - term_lower, rate(lower, upper), rel_tol=3e-15
        )

# Gross vacuum values generated by the page.
checks = {
    (1, 2): 121.568446,
    (2, 3): 656.469606,
    (2, 4): 486.273782,
    (2, 5): 434.173020,
    (2, 6): 410.293504,
    (3, 4): 1875.627447,
}
for transition, expected in checks.items():
    got = wavelength_nm(*transition)
    assert abs(got - expected) < 5e-7, (transition, got, expected)

# Pope's scale mass is distinct from the electron mass.
m_r = H * NU_R / C**2
assert abs(m_r - 2.42411489047825e-35) < 1e-49
assert M_E / m_r > 37_000

# Both displayed radius formulae evaluate to lengths and the printed values.
r_g = HBAR**2 / (G * M_E**2 * M_P)
r_spin = HBAR / math.sqrt(2 * M_E * E_R)
assert abs(r_g / 1.2005239279830703e29 - 1) < 1e-12
assert abs(r_spin / 5.293212903942841e-11 - 1) < 1e-12

source = Path(__file__).resolve().parents[1] / "balmer-rydberg-poams.html"
html = source.read_text()
required = [
    "function lineRate(N, n)",
    "function lineWavelengthNm(N, n)",
    "seriesSelect.addEventListener('change', syncSeriesControls)",
    "The inverse-square <em>shape</em> follows from those premises",
    "Both equations now have dimensions of length",
]
for needle in required:
    assert needle in html, needle

for forbidden in [
    "const spectralLines =",
    "RYDBERG_CONSTANT",
    "G^* m_e M_p}{\\hbar^2",
    "\\hbar^2}{m_e E_{spin}",
    "Math.random()",
]:
    assert forbidden not in html, forbidden

print(
    "PASS balmer-rydberg:",
    f"nu_R={NU_R:.9e} Hz",
    f"m_R={m_r:.9e} kg",
    f"r_G={r_g:.9e} m",
    f"r_spin={r_spin:.9e} m",
)
