#!/usr/bin/env python3
"""Deterministic release checks for The Solar System exhibit."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "solar-system.html"
REDIRECT = ROOT / "ladder-of-octaves.html"
REFERENCE = ROOT / "hotson-octave-tables-reference.html"
RESONANCE = ROOT / "resonance-network.html"
DATA = ROOT / "solar-system-jpl.json"
JS_DATA = ROOT / "solar-system-jpl.js"


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def main() -> None:
    page = PAGE.read_text(encoding="utf-8")
    redirect = REDIRECT.read_text(encoding="utf-8")
    reference = REFERENCE.read_text(encoding="utf-8")
    resonance = RESONANCE.read_text(encoding="utf-8")
    payload = json.loads(DATA.read_text(encoding="utf-8"))
    js_data = JS_DATA.read_text(encoding="utf-8")

    planets = payload["heliocentric"]
    satellites = payload["satellites"]
    require(payload["schema"] == "poams.solar-system-jpl.v1", "unexpected data schema")
    require(len(planets) == 13, "heliocentric census must contain 13 bodies")
    require(sum(body["family"] == "planet" for body in planets) == 8, "planet census must contain 8 planets")
    require(len(satellites) == 46, "satellite census must contain 46 characterized bodies")
    require(sum(body["prominence"] == "major" for body in satellites) == 20, "major-display satellite count changed")
    require(all(body["period_days"] > 0 for body in planets + satellites), "every body needs a positive orbital period")
    require({body["host"] for body in satellites} == {"Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"}, "unexpected satellite host census")

    required_page_phrases = (
        "one observable · no fitted rung",
        "so its color is not a resonance verdict",
        "A slow beat is necessary, never sufficient",
        "imported resonance dynamics supplies the tested phase-angle form",
        "The asteroid belt: destructive closure written as absence",
        "30-year consistency check",
        "adjacent bins near 457 and 498 days",
        "Eight-family history ledger",
        "Lykawka, Horner &amp; Bernardinelli (2026)",
        "Registered n-centre derivation and audit record",
        "resonance can preserve",
        "not destruction of matter",
        "Integer closure alone therefore does not predict clearing",
        "hotson-octave-tables-reference.html",
        "solar-system-jpl.json",
        "0.844° span",
        "159.68° span",
        "4/4 forward-width gates pass",
        "339 times denser",
        "eight published history families",
    )
    for phrase in required_page_phrases:
        require(phrase in page, f"missing release guard: {phrase}")

    forbidden_live_claims = (
        "Why Powers of 2?",
        "One ladder from atoms to planets",
        "The entire solar system is organized by powers of two",
        "Nesvorný et al. (2026)",
        "with a 476.48-day slow period",
        "direct 30-year angles",
        "direct inclination lock",
        "The eight-family audit does this",
    )
    for phrase in forbidden_live_claims:
        require(phrase not in page, f"retired claim leaked into replacement: {phrase}")
    require("WORKING DRAFT" not in page, "working-draft notice remains after ratification")
    require("NOT YET PUBLISHED" not in page, "pre-publication notice remains after ratification")

    ids = re.findall(r'\bid=["\']([^"\']+)["\']', page)
    require(len(ids) == len(set(ids)), "duplicate HTML id in replacement")
    require("let best={p:1,q:1,d:Math.abs(r-1)}" in page, "1:1 screen candidate missing")
    require(page.count("function hostBodies(host,scope)") == 1, "duplicate hostBodies implementation")
    local_targets = re.findall(r'(?:href|src)=["\']\.\/([^"\'#?]+)', page)
    for target in local_targets:
        require((ROOT / target).exists(), f"broken local link: {target}")
    require("HISTORICAL REFERENCE" in reference, "Hotson page is not labeled as historical")
    require("NOT A POAMS RESULT" in reference, "Hotson page lacks doctrine boundary")
    require("unratified zero-remainder" not in resonance, "companion page carries stale ratification state")
    require("missing disc/tidal/spin reservoir history" not in resonance, "companion page carries stale history state")
    require("solar-system.html" in redirect, "legacy URL does not redirect to canonical exhibit")
    require(js_data.startswith("// Generated by scripts/solar_system_data.py"), "JS snapshot lacks provenance banner")
    require("window.SOLAR_SYSTEM_JPL" in js_data, "JS snapshot lacks browser payload")

    print("PASS: 59-body census, doctrine labels, provenance links, and retired-claim guards")


if __name__ == "__main__":
    main()
