/* Display only: numerical results are generated by whole_atom_build.py. */
((catalogue) => {
  'use strict';
  const data = window.POAMS_WHOLE_ATOM;
  if (!data || !document.getElementById('whole-atom-helium')) return;
  const el = id => document.getElementById(id);
  const set = (id, value) => { el(id).textContent = value; };
  const fmt = (n, digits=6) => Number(n).toPrecision(digits);
  const aPM=data.units.length_m*1e12;
  const priorities=new Set([6,7,8]);
  const selector=el('wa-element');
  selector.replaceChildren(...catalogue.map(atom=>{
    const status=atom.n===1?'exact response control':atom.n===2?'calculated ⁴He':priorities.has(atom.n)?'priority · pending':'pending';
    return new Option(`${atom.n} · ${atom.name} (${atom.symbol}) — ${status}`,String(atom.n));
  }));
  selector.value='2';
  set('wa-mean',fmt(data.envelope.mean_pm)+' pm');
  set('wa-rms',fmt(data.envelope.rms_pm)+' pm');
  set('wa-separation',fmt(data.envelope.mean_separation_pm)+' pm');
  set('wa-radius90',data.envelope.radius90_pm.toFixed(2)+' pm');
  set('wa-response',fmt(data.response.finite));
  set('wa-ie',data.comparisons.first_removal_eV.toFixed(6));
  set('wa-baseline-ie',data.uncorrelated_baseline.first_removal_eV.toFixed(5));
  const interval=data.energy_account.find(r=>r.key==='removal_interval');
  set('wa-removal',fmt(interval.rate_PHz)+' PHz');
  el('wa-energy-table').replaceChildren(...data.energy_account.filter(r=>r.key!=='removal_interval').map(r=>{
    const tr=document.createElement('tr');
    for(const value of [r.label,(r.rate_PHz>0?'+':'')+fmt(r.rate_PHz),(r.energy_eV>0?'+':'')+fmt(r.energy_eV)]){
      const td=document.createElement('td');td.textContent=value;tr.append(td);
    }
    if(r.key==='energy')tr.className='wa-total';
    return tr;
  }));
  function frame(id, bounds, xTitle, yTitle){
    const canvas=el(id),w=canvas.clientWidth,h=canvas.clientHeight;
    if(!w||!h)return null;
    const dpr=Math.min(window.devicePixelRatio||1,3);
    if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){
      canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);
    }
    const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);
    const light=document.body.getAttribute('data-theme')==='light';
    const colors={bg:light?'#f8f6ef':'#111820',text:light?'#332d21':'#d4dce4',grid:light?'#d9d4c7':'#30404a',gold:light?'#87630b':'#e3b958',grey:light?'#737780':'#92a0ae',blue:light?'#087792':'#59c7e0'};
    ctx.fillStyle=colors.bg;ctx.fillRect(0,0,w,h);ctx.font='12px system-ui';
    const left=57,right=15,top=39,bottom=47;
    const [xmin,xmax,ymin,ymax]=bounds;
    const x=v=>left+(v-xmin)/(xmax-xmin)*(w-left-right);
    const y=v=>h-bottom-(v-ymin)/(ymax-ymin)*(h-top-bottom);
    ctx.lineWidth=1;
    for(let i=0;i<=4;i++){
      const yy=ymin+(ymax-ymin)*i/4;
      ctx.strokeStyle=colors.grid;ctx.beginPath();ctx.moveTo(left,y(yy));ctx.lineTo(w-right,y(yy));ctx.stroke();
      ctx.fillStyle=colors.text;ctx.textAlign='right';ctx.fillText(Math.abs(yy)<1e-12?'0':Number(yy.toPrecision(2)).toString(),left-7,y(yy)+4);
    }
    for(let i=0;i<=4;i++){
      const xx=xmin+(xmax-xmin)*i/4;
      ctx.textAlign='center';ctx.fillStyle=colors.text;ctx.fillText(Number(xx.toPrecision(3)).toString(),x(xx),h-bottom+20);
    }
    ctx.textAlign='left';ctx.fillText(yTitle,left,19);
    ctx.textAlign='center';ctx.fillText(xTitle,(left+w-right)/2,h-8);
    return {ctx,x,y,w,h,colors,left,right,top,bottom};
  }
  function line(f,points,color,dash=[]){
    const {ctx,x,y}=f;ctx.save();ctx.beginPath();ctx.rect(f.left,f.top,f.w-f.left-f.right,f.h-f.top-f.bottom);ctx.clip();
    ctx.strokeStyle=color;ctx.lineWidth=2;ctx.setLineDash(dash);ctx.beginPath();
    points.forEach(([a,b],i)=>i?ctx.lineTo(x(a),y(b)):ctx.moveTo(x(a),y(b)));ctx.stroke();ctx.restore();
  }
  function drawRadial(){
    const f=frame('wa-radial',[0,180,0,.025],'Distance from compact eye (pm)','Radial probability per pm');
    if(!f)return;
    const points=data.envelope.radial_profile.filter(r=>r.radius_pm<=181).map(r=>[r.radius_pm,r.probability_per_pm]);
    const z=data.uncorrelated_baseline.zeta;
    line(f,points.map(([r])=>{const rho=r/aPM;return[r,4*z**3*rho**2*Math.exp(-2*z*rho)/aPM];}),f.colors.grey,[5,5]);
    line(f,points,f.colors.gold);
    const mean=data.envelope.mean_pm;
    line(f,[[mean,0],[mean,.021]],f.colors.blue,[3,4]);
    f.ctx.fillStyle=f.colors.blue;f.ctx.textAlign='left';f.ctx.fillText('mean',f.x(mean)+5,f.y(.021));
  }
  function responseValues(){
    const helium=selector.value==='2';
    const full=helium?data.response.finite:4.5;
    const chi=el('wa-space').value==='occupied'?0:full;
    const force=Number(el('wa-force').value)*1e-3;
    const shift=-.5*chi*force*force*data.units.rate_Hz/1e9;
    const displacement=-chi*force*aPM/(helium?2:1);
    return {helium,full,chi,force,shift,displacement};
  }
  function drawResponse(){
    if(!['1','2'].includes(selector.value))return;
    const r=responseValues();
    set('wa-force-label',(r.force*1e3).toFixed(2));
    set('wa-shift',`Δ(E/h) = ${Math.abs(r.shift)<1e-12?'0':r.shift.toFixed(5)} GHz · χ = ${fmt(r.chi)}`);
    set('wa-displacement',`Mean relative displacement per mobile entry: ${Math.abs(r.displacement)<1e-12?'0':r.displacement.toFixed(6)} pm. ${r.helium?'Helium-4 includes compact-component recoil.':'Hydrogen is the exact infinite-compact-inertia control.'}`);
    const max=.5*r.full*1e-6*data.units.rate_Hz/1e9;
    const f=frame('wa-curve',[-1,1,-max*1.12,max*.08],'Perturbation F (×10⁻³)','Energy-rate shift (GHz)');
    if(!f)return;
    const xs=Array.from({length:121},(_,i)=>-1+i/60);
    const fullCurve=xs.map(v=>[v,-.5*r.full*v*v*1e-6*data.units.rate_Hz/1e9]);
    line(f,fullCurve,f.colors.grey,[5,4]);
    line(f,xs.map(v=>[v,-.5*r.chi*v*v*1e-6*data.units.rate_Hz/1e9]),f.colors.gold);
    f.ctx.fillStyle=f.colors.blue;f.ctx.beginPath();f.ctx.arc(f.x(r.force*1e3),f.y(r.shift),4,0,2*Math.PI);f.ctx.fill();
  }
  let queued=false;
  const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;drawRadial();drawResponse();});};
  function renderSelection(){
    const atom=catalogue.find(item=>item.n===Number(selector.value));
    const hydrogen=atom.n===1,helium=atom.n===2,available=hydrogen||helium;
    const counts=window.POAMSAtomicLedger.counts(atom.n,atom.massNumber);
    const ratio=Number(counts.ratio.toPrecision(6));
    set('wa-selected-name',`${atom.name} (${atom.symbol})`);
    set('wa-status',hydrogen?'Exact static-response control available':helium?'Helium-4 envelope and response calculated':priorities.has(atom.n)?'Molecules priority — whole-atom calculation pending':'Whole-atom calculation pending');
    set('wa-count-summary',`Count example ${atom.symbol}-${atom.massNumber}: ${counts.depth} depth : ${counts.pattern} pattern; ratio ${ratio} : 1.`);
    set('wa-scope',hydrogen
      ?'The response below is the one-entry, infinite-compact-inertia control, not a finite-isotope or internally resolved core calculation.'
      :helium?'The results below apply to the helium-4 effective external-atom model, not every helium isotope or the compact core’s internal structure.'
      :'Only the inherited isotope-count assignment is available here. Physical dimensions, regional energies and directional response have not been calculated for this element.');
    el('wa-helium-results').hidden=!helium;
    el('wa-hydrogen-results').hidden=!hydrogen;
    el('whole-atom-response').hidden=!available;
    el('wa-benchmarks').hidden=!available;
    el('wa-pending').hidden=available;
    if(available){
      set('wa-response-species',hydrogen?'Showing hydrogen’s exact infinite-compact-inertia response control. Choose an element above to change the available result.':'Showing helium-4’s calculated response, including compact recoil. Choose an element above to change the available result.');
      drawResponse();
    }else{
      set('wa-next',priorities.has(atom.n)
        ?`${atom.name} is one of the C/N/O response priorities before the next long Molecules run. Its occupied state and complete directional response must be calculated and checked; it is not a rescaled helium result.`
        :`${atom.name} needs its own many-entry state and response calculation. This selector records the open work; it does not launch a solve. The C/N/O molecular-input calculations take priority.`);
      set('wa-shift','');set('wa-displacement','');
    }
    schedule();
  }
  selector.addEventListener('change',renderSelection);
  el('wa-count-link').addEventListener('click',()=>{
    el('al-element').value=selector.value;
    el('al-element').dispatchEvent(new Event('change',{bubbles:true}));
  });
  for(const id of ['wa-space','wa-force'])el(id).addEventListener('input',drawResponse);
  // Keep existing links into helium details usable after another element was selected.
  function revealAtomicLink(){
    const hash=window.location.hash;
    const target=el(hash.slice(1));
    const needsHelium=hash==='#whole-atom-helium'||el('wa-helium-results').contains(target);
    const needsAvailable=(hash==='#whole-atom-response'||el('wa-benchmarks').contains(target))&&!['1','2'].includes(selector.value);
    if(needsHelium||needsAvailable){selector.value='2';renderSelection();}
    schedule();
  }
  new ResizeObserver(schedule).observe(el('whole-atom-helium'));
  new MutationObserver(schedule).observe(document.body,{attributes:true,attributeFilter:['data-theme']});
  window.addEventListener('resize',schedule);window.addEventListener('hashchange',revealAtomicLink);
  renderSelection();
})(elements);
